# Generated by Django 4.1.2 on 2023-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komapp', '0005_alter_town_townname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicians',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
