# Generated by Django 4.1.2 on 2023-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komapp', '0006_alter_magicians_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kings',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='superheroes',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='town',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='villians',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
