# Generated by Django 4.1.2 on 2023-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komapp', '0007_alter_kings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kings',
            name='photoFilename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='magicians',
            name='photoFilename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superheroes',
            name='photoFilename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='town',
            name='photoFilename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='villians',
            name='photoFilename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
